---
- name: Install pip dependencies for running the unit and functional tests.
  pip:
    requirements: "{{ test_pip_requirements }}"
  tags:
    - pip

- name: Install testing package dependencies.
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ test_apt_dependencies }}"
  tags:
    - apt

- name: Copy xvfb init script (Trusty)
  copy:
    src: xvfb
    dest: /etc/init.d/xvfb
    owner: root
    mode: "0700"
  # Trusty uses upstart/sysv-style init scripts
  when: ansible_distribution_release == "trusty"
  tags:
    - xvfb
    - permissions

- name: Update rc.d to run xvfb at boot (Trusty)
  command: update-rc.d xvfb defaults
  register: xvfb_setup
  changed_when: "'System start/stop links for /etc/init.d/xvfb already exist' not in xvfb_setup.stdout"
  when: ansible_distribution_release == "trusty"
  notify: start xvfb
  tags:
    - xvfb

- name: Copy xvfb init script (Xenial)
  copy:
    src: xvfb-systemd
    dest: /etc/systemd/system/xvfb.service
    owner: root
    mode: "0644"
  # Xenial uses systemd, so upstart/sysv init scripts won't work
  when: ansible_distribution_release == "xenial"
  notify: start xvfb
  tags:
    - xvfb
    - permissions

- name: Update xvfb service to run at boot (Xenial)
  service:
    name: xvfb
    enabled: yes
  when: ansible_distribution_release == "xenial"
  tags:
    - xvfb

- name: Set DISPLAY environment variable for xvfb.
  copy:
    src: xvfb_display.sh
    dest: /etc/profile.d/xvfb_display.sh
    owner: root
    mode: "0444"
  tags:
    - xvfb
    - environment
    - permissions
