---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: tor-package-fetcher-xenial

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: fetch-tor-packages
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  options:
    connection: docker
  lint:
    name: flake8
