---
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: trusty-sd-builder
    # Trusty from 2017-12-15
    image: ubuntu@sha256:084989eb923bd86dbf7e706d464cf3587274a826b484f75b69468c19f8ae354c
    groups:
      - build
provisioner:
  name: ansible
  inventory:
    links:
      # Path is relative to .molecule folder
      group_vars: ../../../install_files/ansible-base/group_vars
  env:
    ANSIBLE_ROLES_PATH: ../../install_files/ansible-base/roles
    ANSIBLE_ACTION_PLUGINS: ../../install_files/ansible-base/action_plugins
  lint:
    name: ansible-lint
scenario:
  name: builder
  test_sequence:
    - destroy
    - create
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  options:
    # provided by pytest-xdist
    n: auto
  lint:
    name: flake8
