---
install_local_packages: true
primary_network_iface: eth0
app_ip: "{{ hostvars['app-staging']['ansible_'+primary_network_iface].ipv4.address }}"
monitor_ip: "{{ hostvars['mon-staging']['ansible_'+primary_network_iface].ipv4.address }}"
ssh_users: sdrop
enable_ssh_over_tor: false
ssh_net_in_override: 0.0.0.0/0
